package com.passwordmemo.sky.passwordmemo.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_PASSWORD".
 */
public class UserPassword {

    private Long id;
    private Long adminId;
    private String describe;
    private String account;
    private String password;

    public UserPassword() {
    }

    public UserPassword(Long id) {
        this.id = id;
    }

    public UserPassword(Long id, Long adminId, String describe, String account, String password) {
        this.id = id;
        this.adminId = adminId;
        this.describe = describe;
        this.account = account;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdminId() {
        return adminId;
    }

    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    public String getDescribe() {
        return describe;
    }

    public void setDescribe(String describe) {
        this.describe = describe;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
